### ISSUE TITLE
Desktop AND app versions won't make a tally

### ISSUE THREAD

**Issue by schmutzie** [GenderAvenger/gatally#22]
I tried using the desktop AND app versions to create a tally. It lets me enter the numbers, but when I hit enter after I input the title and hashtag, it just boots me back to the numbers page to start again.

**Comment by slifty** [comment]
This was quickly fixed up; the issue was that validation of the title and hashtag fields routed to the wrong form.  This meant if there was anything wrong with the hashtag or the title the user would be sent back to the counting form (with no values filled out), making it look like everything was broken.

Validation is now properly routing.
