### ISSUE TITLE
Instagram integration

### ISSUE THREAD

**Issue by jrvento** [GenderAvenger/gatally#39]
**Describe the solution you'd like**
Integrate the ability to share tally results on Instagram, similar to existing functionality for Twitter and Facebook.

**Comment by slifty** [comment]
We discussed how this would work last Friday by phone -- specifically that we would create a fifth button on the share page (as opposed to replacing one of the existing buttons)

**Comment by slifty** [comment]
I spent some time looking at this and shared the results in Slack a few weeks ago, but did not log the findings here.

Instagram, by design, does not have a way to push images into it from third party sources.  This means we aren't going to be able to have a button that publishes to Instagram.  Unfortunately that means this issue will not be possible to complete.

Instead I will be opening an issue for creating a button that allows users to "save" the tally image to their local file system (which they could then upload to Instagram on their own, or use anywhere else for that matter).
